#--- docker-compose-prod.yml (blue, green) ---
version: '3'
services:
  napzak-prod-blue:
    container_name: napzak-prod-blue
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - "8081:8080"
    networks:
      - napzak-prod-net

  napzak-prod-green:
    container_name: napzak-prod-green
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - "8082:8080"
    networks:
      - napzak-prod-net

networks:
  napzak-prod-net:
    driver: bridge
