#--- docker-compose-dev.yml (blue, green) ---
version: '3'
services:
  napzak-dev-blue:
    container_name: napzak-dev-blue
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8081:8080"
    networks:
      - napzak-dev-net

  napzak-dev-green:
    container_name: napzak-dev-green
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8082:8080"
    networks:
      - napzak-dev-net

networks:
  napzak-dev-net:
    driver: bridge
