version: '3'
services:
  napzak-prod-blue:
    container_name: napzak-prod-blue
    image: "sailin1367/napzak-prod:latest"
    ports:
      - "8081:8080"
    networks:
      - napzak-prod-net

  napzak-prod-green:
    container_name: napzak-prod-green
    image: "sailin1367/napzak-prod:latest"
    ports:
      - "8082:8080"
    networks:
      - napzak-prod-net

networks:
  napzak-prod-net:
    driver: bridge
