version: "3.8"

services:
  napzak-prod:
    container_name: napzak-prod
    image: "sailin1367/napzak-prod:latest"
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - napzak-prod-net

  redis:
    container_name: napzak-prod-redis
    image: redis:7.0-alpine
    command: ["redis-server", "--requirepass", "napzakprod"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "napzakprod", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - napzak-prod-net
    deploy:
      restart_policy:
        condition: none

networks:
  napzak-prod-net:
    driver: bridge