version: '3'
services:
  napzak-dev-blue:
    container_name: napzak-dev-blue
    # GitHub Actions가 푸시한 Docker Hub 이미지
    image: "sailin1367/napzak-dev:latest"
    ports:
      - "8081:8080"
    networks:
      - napzak-dev-net

  napzak-dev-green:
    container_name: napzak-dev-green
    # 똑같이 latest 태그 사용 (blue/green 둘 다 동일 이미지)
    image: "sailin1367/napzak-dev:latest"
    ports:
      - "8082:8080"
    networks:
      - napzak-dev-net

networks:
  napzak-dev-net:
    driver: bridge
