name: prod-CD

on:
  push:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-22.04
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: create secret config file
        run: |
          cd src/main/resources
          echo "${{ secrets.APPLICATION_PROD }}" > ./application-prod.yml

      - name: build with gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.PROD_DOCKERHUB_USERNAME }}
          password: ${{ secrets.PROD_DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile-prod
          push: true
          tags: ${{ secrets.PROD_DOCKERHUB_USERNAME }}/${{ secrets.PROD_REPONAME }}:latest

  CD:
    needs: [CI]
    runs-on: ubuntu-22.04
    environment: prod

    steps:
      - name: Docker Image Pull and Container Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          key: ${{ secrets.PROD_SERVER_KEY }}
          script: |
            # 2) /home/ubuntu/35-APPJAM-SERVER-NAPZAKMARKET 디렉토리로 이동
            cd /home/ubuntu/35-APPJAM-SERVER-NAPZAKMARKET
            
            # 3) .env 파일 작성
            echo "REDIS_PASSWORD=${{ secrets.PROD_REDIS_PASSWORD }}" > .env

            # 4) docker-compose pull + up
            docker-compose --env-file .env pull napzak-prod
            docker-compose --env-file .env up -d --remove-orphans

            # 5) 로그 확인
            docker logs napzak-prod
            docker logs napzak-prod-redis

            # 6) .env 파일 삭제
            rm .env
